# docker-compose.yml

---
services:
  app:
    restart: unless-stopped
    volumes:
      - ${GLOBAL_DATA_FOLDER:-/Data}/recipya/data:/home/recipya/.config/Recipya
    environment:
      RECIPYA_SERVER_PORT: 8078
      RECIPYA_SERVER_NO_SIGNUPS: ${RECIPYA_SERVER_NO_SIGNUPS:-false}
      RECIPYA_SERVER_AUTOLOGIN: ${RECIPYA_SERVER_AUTOLOGIN:-true}
      RECIPYA_SERVER_IS_DEMO: ${RECIPYA_SERVER_IS_DEMO:-false}
      RECIPYA_SERVER_IS_PROD: ${RECIPYA_SERVER_IS_PROD:-true}
      RECIPYA_SERVER_URL: https://${SERVICE_NAME_OVERRIDE:-recipya}.${DOMAIN_NAME:-local}
      TZ: ${TZ:-Etc/UTC}
    image: docker.io/reaper99/recipya:${RECIPYA_VERSION:-v1.2.2}
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.docker.network: traefik_default
      traefik.enable: true
      traefik.http.routers.recipya.entrypoints: websecure
      traefik.http.routers.recipya.rule: Host(`${SERVICE_NAME_OVERRIDE:-recipya}.${DOMAIN_NAME:-local}`)
      traefik.http.routers.recipya.service: recipya
      traefik.http.routers.recipya.tls: true
      traefik.http.routers.recipya.tls.certresolver: ${LETSENCRYPT_CERTRESOLVER:-letsencrypt-cloudflare-dns-challenge}
      traefik.http.services.recipya.loadbalancer.server.port: 8078
    networks:
      - traefik_default
networks:
  default: null
  traefik_default:
    external: true
x-dockge:
  urls:
    - https://${SERVICE_NAME_OVERRIDE:-recipya}.${DOMAIN_NAME:-local}
