# docker-compose.yml

---
services:
  app:
    image: lscr.io/linuxserver/grocy:${GROCY_VERSION:-latest}
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-100}
      TZ: ${TZ:-Etc/UTC}
    volumes:
      - ${GLOBAL_DATA_FOLDER:-/Data}/grocy/config:/config
    restart: unless-stopped
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.docker.network: traefik_default
      traefik.enable: true
      traefik.http.routers.grocy.entrypoints: websecure
      traefik.http.routers.grocy.rule: Host(`${SERVICE_NAME_OVERRIDE:-grocy}.${DOMAIN_NAME:-local}`)
      traefik.http.routers.grocy.service: grocy
      traefik.http.routers.grocy.tls: true
      traefik.http.routers.grocy.tls.certresolver: ${LETSENCRYPT_CERTRESOLVER:-letsencrypt-cloudflare-dns-challenge}
      traefik.http.services.grocy.loadbalancer.server.port: 80
    networks:
      - traefik_default
networks:
  traefik_default:
    external: true
x-dockge:
  urls:
    - https://${SERVICE_NAME_OVERRIDE:-grocy}.${DOMAIN_NAME:-local}
